ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.halyxsynck.HttpKt.configureHttp
      - com.halyxsynck.SerializationKt.configureSerialization
      - com.halyxsynck.RoutingKt.configureRouting
